In [2]:
import numpy as np
arr = np.array([10,20,30,40,50])
arr = np.delete(arr,2)
print("resulting array:",arr)

resulting array: [10 20 40 50]


In [7]:
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.concatenate((arr1,arr2))
print("Concatenated array is:",result)

Concatenated array is: [10 20 30 40 50 60]


In [8]:
import numpy as np 
arr = np.array([50,10,40,20,30])
print(np.sort(arr))

[10 20 30 40 50]


In [9]:
import numpy as np 
arr = np.array([10,0,20,0,30,0,40])
print(np.nonzero(arr))

(array([0, 2, 4, 6]),)


In [10]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(np.searchsorted(arr,35))

3


In [11]:
import numpy as np 
arr = np.array([10,20,20,30,10,40,50])
print(np.unique(arr))

[10 20 30 40 50]


In [12]:
import numpy as np 
arr = np.array([10,0,20,0,30,40,0])
print(np.count_nonzero(arr))

4


In [14]:
import numpy as np
arr=np.array([10,20,30])
print(np.repeat(arr,3))

[10 10 10 20 20 20 30 30 30]


In [19]:
import numpy as np 
arr = np.array([85,90,75,88,92])
print(arr)
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.max(arr))
print(np.min(arr))

[85 90 75 88 92]
430
86.0
88.0
92
75


In [27]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)


[10 20 30 40]
1
(4,)
4
int64
8
32


In [31]:
import numpy as np
arr1= np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.stack((arr1,arr2))
print("resulting array:",result)

resulting array: [[10 20 30]
 [40 50 60]]


In [33]:
import numpy as np
arr=np.array([10,20,30,40])
copy_arr = arr.copy()
copy_arr[1]=100

print("Original array:",arr)
print("Copy array:",copy_arr)

Original array: [10 20 30 40]
Copy array: [ 10 100  30  40]
