In [3]:
%pip install numpy


   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.7 MB 13.5 MB/s eta 0:00:01
   -------------- ------------------------- 4.7/12.7 MB 12.3 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.7 MB 12.3 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.7 MB 12.2 MB/s eta 0:00:01
   ------------------------------------- -- 12.1/12.7 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 11.5 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
ids = [101,102,103,104,105]
arr =np.array(ids)

print(arr)

[101 102 103 104 105]


In [7]:
import numpy as np 
t = (100,200,300,400,500)
arr = np.array(t)

print(arr)

[100 200 300 400 500]


In [8]:
import numpy as np

arr = np.arange(5,16)

print(arr)

[ 5  6  7  8  9 10 11 12 13 14 15]


In [2]:
import numpy as np 
arr = np.arange(20,101,10)

print(arr)

[ 20  30  40  50  60  70  80  90 100]


In [4]:

import numpy as np 
arr = np.array(list("DATA"))

print(arr)

['D' 'A' 'T' 'A']


In [5]:
import numpy as np 
status = [True,False,True,True,False]
arr = np.array(status)
print(arr)

[ True False  True  True False]


In [6]:
import numpy as np

arr = np.array([])

print(arr)

[]


In [8]:
import numpy as np 

arr = np.zeros(8)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
import numpy as np 

arr = np.ones(6)
print(arr)

[1. 1. 1. 1. 1. 1.]


In [10]:
import numpy as np 

arr = np.full(10,500)
print(arr)

[500 500 500 500 500 500 500 500 500 500]


In [11]:
import numpy as np 

arr = np.linspace(0,100,5)

print(arr)

[  0.  25.  50.  75. 100.]


In [12]:
import numpy as np

arr = np.linspace(20000,80000,8)

print(arr)

[20000.         28571.42857143 37142.85714286 45714.28571429
 54285.71428571 62857.14285714 71428.57142857 80000.        ]


In [13]:
import numpy as np 

arr = np.arange(1,51,5)

print(arr)


[ 1  6 11 16 21 26 31 36 41 46]


In [15]:
import numpy as np 

arr = np.arange(1,26,2)

print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [17]:
import numpy as np 

arr = np.arange(10,51,2)

print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [19]:
import numpy as np

s= {10,20,30,40,50}
arr = np.array(list(s))
print(arr)

[50 20 40 10 30]


In [20]:
import numpy as np

s= "PYTHON"
arr = np.array(list(s))
print(arr)

['P' 'Y' 'T' 'H' 'O' 'N']


In [22]:
import numpy as np

a = np.array([1,2,3])
b = np.arange(0,10)
c= np.linspace(10, 50, 5)
d = np.zeros(3)
e= np.ones(2)

print(a)
print(b)
print(c)
print(d)
print(e)

[1 2 3]
[0 1 2 3 4 5 6 7 8 9]
[10. 20. 30. 40. 50.]
[0. 0. 0.]
[1. 1.]


# Properties of  1D Array

### 1.ndim
### 2.shape
### 3.size
### 4.dtype
### 5.itemsize
### 6.nbytes


In [26]:
import numpy as np

arr = np.array([10,20,30,40])

print(arr.ndim)

1


In [27]:
import numpy as np

arr = np.array([[10,20,30,40],[1,2,3,4]])

print(arr.ndim)

2


In [28]:
import numpy as np 

arr = np.array([1,2,3,4])

print(arr.shape)

(4,)


In [30]:
import numpy as np 

arr = np.array([[1,2,3,4],[2,4,6,8]])
print(arr.shape)

               

(2, 4)


In [32]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr.size)

5


In [33]:
import numpy as np 
arr = np.array([
    [1,2,3],
    [3,5,7],
])
print(arr.size)


6


In [34]:
import numpy as np 

arr = np .array([1,2,3])
print(arr.dtype)

int64


In [36]:
import numpy as np 
arr = np.array([10,20,30,"40"])
print(arr.dtype)  

<U21


In [37]:
import numpy as np 
arr = np.array([1,2.6,0,])
print(arr.dtype)

float64


In [40]:
import numpy as np
arr = np.array([True ,0,2,0.4])
print(arr.dtype)

float64


In [43]:
import numpy as np 
arr = np.array([10,20,30,"Tejal"])
print(arr.itemsize)

84


In [46]:
import numpy as np
arr =np.array([2.2,2.3])
print(arr.itemsize)


8


In [2]:
import numpy as np 
a=np.array([1,2]) 
b=np.array([3,4]) 
print(np.stack((a,b))) 

[[1 2]
 [3 4]]


In [3]:
import numpy as np
arr=np.array([10,0,20,0,30]) 
print(np.count_nonzero(arr))

3


In [4]:
import numpy as np
arr = np.array(["10","20","30","40"]) 
print(arr.itemsize) 

8


In [5]:
import numpy as np
arr = np.array([10,20,30,40]) 
print(arr.itemsize) 

8


In [6]:
import numpy as np
arr = np.array([1.0,2.0,3.0,4.0]) 
print(arr.itemsize) 

8
